### ISSUE TITLE
Split your lib into separate module

### ISSUE THREAD

**Issue by JanickRoss** [onnohaldar/zgwnu-ng2-bonita#2]
good lib I plan to use it. It is possible to split all bonita api stuff on a separate lib and all component ui on other lib ?

Thanks for our work

**Comment by onnohaldar** [comment]
Thank you for you're suggestion. We have to plan this after a demo for a client this month. For now I added some extra Case functionality because we have to work with documents in our demo.

**Comment by onnohaldar** [comment]
If have finally splitter the api stuff from the component ui (file upload component). Thank you for helping me to make the lib more consistent.
